var searchData=
[
  ['handleposition',['handlePosition',['http://qt-project.org/doc/qt-4.8/q3dockarea.html#handlePosition-prop',0,'Q3DockArea']]],
  ['handlewidth',['handleWidth',['http://qt-project.org/doc/qt-4.8/qsplitter.html#handleWidth-prop',0,'QSplitter']]],
  ['hashotspot',['hasHotSpot',['http://qt-project.org/doc/qt-4.8/qgesture.html#hasHotSpot-prop',0,'QGesture']]],
  ['hasselectedtext',['hasSelectedText',['http://qt-project.org/doc/qt-4.8/q3textedit.html#hasSelectedText-prop',0,'Q3TextEdit::hasSelectedText()'],['http://qt-project.org/doc/qt-4.8/qlineedit.html#hasSelectedText-prop',0,'QLineEdit::hasSelectedText()'],['http://qt-project.org/doc/qt-4.8/qlabel.html#hasSelectedText-prop',0,'QLabel::hasSelectedText()']]],
  ['hasselection',['hasSelection',['http://qt-project.org/doc/qt-4.8/qwebpage.html#hasSelection-prop',0,'QWebPage::hasSelection()'],['http://qt-project.org/doc/qt-4.8/qwebview.html#hasSelection-prop',0,'QWebView::hasSelection()']]],
  ['headerhidden',['headerHidden',['http://qt-project.org/doc/qt-4.8/qtreeview.html#headerHidden-prop',0,'QTreeView']]],
  ['headervisible',['headerVisible',['http://qt-project.org/doc/qt-4.8/qcalendarwidget-obsolete.html#headerVisible-prop',0,'QCalendarWidget']]],
  ['height',['height',['http://qt-project.org/doc/qt-4.8/qwidget.html#height-prop',0,'QWidget']]],
  ['highlightsections',['highlightSections',['http://qt-project.org/doc/qt-4.8/qheaderview.html#highlightSections-prop',0,'QHeaderView']]],
  ['historytype',['historyType',['http://qt-project.org/doc/qt-4.8/qhistorystate.html#historyType-prop',0,'QHistoryState']]],
  ['horizontaldirection',['horizontalDirection',['http://qt-project.org/doc/qt-4.8/qswipegesture.html#horizontalDirection-prop',0,'QSwipeGesture']]],
  ['horizontalheaderformat',['horizontalHeaderFormat',['http://qt-project.org/doc/qt-4.8/qcalendarwidget.html#horizontalHeaderFormat-prop',0,'QCalendarWidget']]],
  ['horizontallystretchable',['horizontallyStretchable',['http://qt-project.org/doc/qt-4.8/q3dockwindow.html#horizontallyStretchable-prop',0,'Q3DockWindow']]],
  ['horizontalscrollbarpolicy',['horizontalScrollBarPolicy',['http://qt-project.org/doc/qt-4.8/qabstractscrollarea.html#horizontalScrollBarPolicy-prop',0,'QAbstractScrollArea']]],
  ['horizontalscrollmode',['horizontalScrollMode',['http://qt-project.org/doc/qt-4.8/qabstractitemview.html#horizontalScrollMode-prop',0,'QAbstractItemView']]],
  ['horizontalspacing',['horizontalSpacing',['http://qt-project.org/doc/qt-4.8/qformlayout.html#horizontalSpacing-prop',0,'QFormLayout::horizontalSpacing()'],['http://qt-project.org/doc/qt-4.8/qgridlayout.html#horizontalSpacing-prop',0,'QGridLayout::horizontalSpacing()']]],
  ['hotspot',['hotSpot',['http://qt-project.org/doc/qt-4.8/qgesture.html#hotSpot-prop',0,'QGesture']]],
  ['hscrollbarmode',['hScrollBarMode',['http://qt-project.org/doc/qt-4.8/q3scrollview.html#hScrollBarMode-prop',0,'Q3ScrollView']]],
  ['html',['html',['http://qt-project.org/doc/qt-4.8/qtextedit.html#html-prop',0,'QTextEdit']]],
  ['hue',['hue',['http://qt-project.org/doc/qt-4.8/phonon-videowidget.html#hue-prop',0,'Phonon::VideoWidget']]]
];
